routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//=============== MAIN\PUBLIC ROUTES ===================

 // ===== GET ROUTES ========

Route::get('/', 'HomeController@homepage')->name('home');
 
Auth::routes();

Route::get('/profile', 'HomeController@profile')->name('profile');
Route::patch('/profile', 'HomeController@profileUpdateSettings')->name('profile.update');

//Route::get('/home', 'HomeController@cp')->name('CP');

// Public animes page
Route::get('/anime', 'HomeController@animeMain')->name('anime');
Route::get('/anime/{show}', 'HomeController@showAnime')->name('anime.show');

// Public TV Shows page

Route::get('/tvshows', 'HomeController@tvShowsMain')->name('tvshows');
Route::get('/tvshows/{show}', 'HomeController@showTvShows')->name('tvshows.show');

// Public films page

Route::get('/films', 'HomeController@filmsMain')->name('films');
Route::get('/films/{show}', 'HomeController@showFilms')->name('films.show');

// Public OVAs page

Route::get('/ova', 'HomeController@ovaMain')->name('ova');
Route::get('/ova/{show}', 'HomeController@showOva')->name('ova.show');

// ====== POST ROUTES =========



//======= RESOURCES ==========


  // ADMIN


//======= ADMIN AREA ======== 
Route::group(['prefix' => 'cp'], function() {

Route::get('/', 'ControlPanelController@index')->name('CP');

Route::resource('anime', 'AnimeController');
Route::resource('film', 'FilmController');
Route::resource('tv-show', 'TvShowController');
Route::resource('oav', 'OavController');

});
//Route::get('/cp/animes', 'ControlPanelController@getAnime')->name('cp.anime.show');
// Anzichè fare un controller e una risorsa per ogni categorie che abbiamo
// mi è sembrato più logico farne uno unico per tutto quanto, e lasciare
// decidere cosa fare alla logica nel controller, in base alla
// variabile utilizzata  showtype
//Route::resource('cp/{showtype}/{show}', 'ShowController');

resources/views/admin/index.blade.php
@extends('layouts.adminLayout')
@section('content')
<div class="spacer my-4"></div>
<div class="container">
	<div class="row mb-3 mt-2">
		<h1>Pannello di Controllo</h1>
		<p><strong><span class="red">Attenzione</span> : Sei in un'area sensibile. Qualunque azione eseguita dal pannello di controllo è solitamente permanente, attenti a cosa fate. </strong></p>
	</div>
	<div class="row">
	
<div class="col-4">
	<div class="card cpCard" style="">
	  <div class="card-body">
	    <h5 class="card-title">Card title</h5>
	    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
	    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
	    <a href="#" class="card-link">Card link</a>
	    <a href="#" class="card-link">Another link</a>
	  </div>
	</div>
</div>
<div class="col-4">
	<div class="card cpCard" style="">
	  <div class="card-body">
	    <h5 class="card-title">Card title</h5>
	    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
	    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
	    <a href="#" class="card-link">Card link</a>
	    <a href="#" class="card-link">Another link</a>
	  </div>
	</div>
</div>
<div class="col-4">
	<div class="card cpCard" style="">
	  <div class="card-body">
	    <h5 class="card-title">Card title</h5>
	    <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
	    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
	    <a href="#" class="card-link">Card link</a>
	    <a href="#" class="card-link">Another link</a>
	  </div>
	</div>
</div>
</div>
</div>



@endsection

resources/views/admin/shows-edit.blade.php
@extends('layouts.adminLayout')
@section('content')
<div class="container">
	<div class="row">
		<div class="card">
			<div class="card-header">Modifica {{ $show->name }}</div>
			<div class="card-body">
				<p class="card-text">Tipo : {{ $type->name }}</p>
				<p class="card-text">
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/admin/shows.blade.php
@extends('layouts.adminLayout')
@section('content')
<div class="spacer my-4"></div>
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1>Elenco Anime</h1>
			<hr>
		</div>
	</div>
	@foreach($animes->chunk(3) as $anime)
	<div class="card-deck mb-3"> <!-- /row - /card-deck -->
		@foreach($anime as $entry)
	<div class="card">
	<img class="card-img-top" src="http://via.placeholder.com/150x150" alt="Cover di {{ $entry->name }}">
	  <div class="card-body">
	    <h5 class="card-title">{{ $entry->name }}</h5>
	    <p class="card-text"><small class="text-muted">Trama</small></p>
	    <p class="card-text">{{ str_limit($entry->plot, 100, '...') }}</p>
	  </div>
	  <ul class="list-group list-group-flush">
	    <li class="list-group-item">Ultimo episodio aggiunto {{ $entry->episodes()->latest()->first()->created_at->diffForHumans() }}</li>
	    <li class="list-group-item">Titolo ultimo episodio : {{ $entry->episodes()->latest()->first()->name }}</li>
	    <li class="list-group-item">Punteggio : {{ $entry->points }}</li>
	  </ul>
	  <div class="card-body">
	    <a href="{{ route('cp.anime.show', ['type' => $typeSlug, 'show' => $entry->slug]) }}" class="card-link">Visualizza</a>
	    <a href="{{ route('cp.anime.edit', ['type' => $typeSlug, 'show' => $entry->slug]) }}" class="card-link">Modifica</a>
	    <a href="{{ route('cp.anime.delete', ['type' => $typeSlug, 'show' => $entry->slug]) }}" type="button" class="card-link">Elimina</a>
	  </div>
	</div>
  		@endforeach
	</div> <!-- end /row - end /card-deck -->
	@endforeach
	<div class="row">
		<div class="col-12 text-center">
			{{ $animes->links() }}
		</div>
	</div>

@endsection