routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//=============== MAIN\PUBLIC ROUTES ===================

 // ===== GET ROUTES ========

Route::get('/', 'HomeController@homepage')->name('home');
 
Auth::routes();

Route::get('/profile', 'HomeController@profile')->name('profile');
Route::patch('/profile', 'HomeController@profileUpdateSettings')->name('profile.update');

//Route::get('/home', 'HomeController@cp')->name('CP');

// Public animes page
Route::get('/anime', 'HomeController@animeMain')->name('anime');
Route::get('/anime/{show}', 'HomeController@showAnime')->name('anime.show');

// Public TV Shows page

Route::get('/tvshows', 'HomeController@tvShowsMain')->name('tvshows');
Route::get('/tvshows/{show}', 'HomeController@showTvShows')->name('tvshows.show');

// Public films page

Route::get('/films', 'HomeController@filmsMain')->name('films');
Route::get('/films/{show}', 'HomeController@showFilms')->name('films.show');

// Public OVAs page

Route::get('/ova', 'HomeController@ovaMain')->name('ova');
Route::get('/ova/{show}', 'HomeController@showOva')->name('ova.show');

// ====== POST ROUTES =========



//======= RESOURCES ==========


  // ADMIN


//======= ADMIN AREA ======== 
Route::group(['prefix' => 'cp'], function() {

Route::get('/', 'ControlPanelController@index')->name('CP');

Route::resource('anime', 'AnimeController');
Route::resource('film', 'FilmController');
Route::resource('tv-show', 'TvShowController');
Route::resource('oav', 'OavController');

});
//Route::get('/cp/animes', 'ControlPanelController@getAnime')->name('cp.anime.show');
// Anzichè fare un controller e una risorsa per ogni categorie che abbiamo
// mi è sembrato più logico farne uno unico per tutto quanto, e lasciare
// decidere cosa fare alla logica nel controller, in base alla
// variabile utilizzata  showtype
//Route::resource('cp/{showtype}/{show}', 'ShowController');

app/Http/Controllers/OavController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Show;
use Carbon\Carbon;

class OavController extends Controller
{
    public function __construct() {
        $this->middleware('auth');
        $this->middleware('checkLevel'); 
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $oavs = Show::whereHas('type', function($query) {
            $query->where('slug', '=', 'oav');
        })->paginate(10);
        return view('admin.oav.index', compact('oavs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($oav)
    {
        $oav = Show::where('slug', $oav)->firstorFail();
        Carbon::setLocale('it');
        return view('admin.oav.show', compact('oav'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($oav)
    {
        $oav = Show::where('slug', $oav)->first();
        $oldSlug = $oav->slug;
        return view('admin.anime.edit', compact('oav', 'oldSlug'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/oav/edit.blade.php
@extends('layouts.adminLayout')
@section('content')
<div class="spacer my-4"></div>
@include('components.back')
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1>Stai modificando <strong>{{ $oav->name }}</strong>, un <strong>{{ $oav->type()->first()->name }}</strong></h1>
		</div>
	</div>
	<div class="row">
		<div class="col-12">
			<form name="editAnime" method="post" action="{{ route('oav.update', ['oav' => $oav->slug]) }}">
				{{ csrf_field() }}
				{{ method_field('PATCH') }}
				<input type="hidden" id="oldSlug" value="{{ $oldSlug }}">
				<div class="form-group">
					<img src="http://via.placeholder.com/150x150">
					<label>Immagine di copertina</label>
					<input type="file" name="image">

				</div>
				<div class="form-group">
					<label>Nome</label>
					<input type="text" class="form-control form-control-lg" placeholder="" value="{{ $oav->name }}" name="nome">
				</div>
				<div class="form-group">
					<label>Slug</label>
					<input type="text" class="form-control form-control-lg" placeholder="" value="{{ $oav->slug }}" name="slug">
				</div>
				<div class="form-group">
					<label>Trama</label>
					<textarea name="plot" rows="25" class="form-control">{{ $oav->plot }}</textarea>
				</div>
				<div class="form-group">
					<div class="col-6">
						<label>Audio</label>
						<select name="audio" class="custom-select form-control">
						  <option value="">Scegli una lingua</option>
						  <option value="ita">ITA</option>
						  <option value="jap">JAP</option>
						  <option value="eng">ENG</option>
						</select>
					</div>
					<div class="col-6">
						<label>Sub</label>
						<select name="sub" class="custom-select">
						  <option value="">Scegli una lingua</option>
						  <option value="ita">ITA</option>
						  <option value="jap">JAP</option>
						  <option value="eng">ENG</option>
						</select>

					</div>
				</div>
				<div class="form-group">
					<div class="col-3">
						<label>Points</label>
						<input type="text" size="4" name="punti" value="{{ $oav->points }}">
					</div>
					<div class="col-9">
						<label>Genere</label>
						<select name="genere" class="custom-select form-control">
						  <option value="">Scegli una genere</option>
						  <option value="ita">ITA</option>
						  <option value="jap">JAP</option>
						  <option value="eng">ENG</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<div class="col-8">
						<label>Paese</label>
						<select name="paese" class="custom-select form-control">
						  <option value="">Scegli una tipo</option>
						  <option value="ita">ITA</option>
						  <option value="jap">JAP</option>
						  <option value="eng">ENG</option>
						</select>
					</div>
					<div class="col-4">
						<label>Tipo</label>
						<select name="tipo" class="custom-select form-control">
						  <option value="">Scegli una tipo</option>
						  <option value="ita">ITA</option>
						  <option value="jap">JAP</option>
						  <option value="eng">ENG</option>
						</select>
					</div>
				</div>
				<div class="form-group">
					<button type="submit" class="btn btn-primary btn-block btn-lg">Conferma Modifiche</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/oav/index.blade.php
@extends('layouts.adminLayout')
@section('content') 
<div class="spacer my-3"></div>

<div class="container">
	<div class="row">
		<div class="col-12">
			<h1>Gli OAV in archivio</h1>
		</div>
		<div class="col-12">
			<table class="table table-striped table-hover table-dark">
			  <thead>
			    <tr>
			      <th scope="col">#</th>
			      <th scope="col">Nome</th>
			      <th scope="col">Paese</th>
			      <th scope="col">Trama</th>
			      <th scope="col">Audio</th>
			      <th scope="col">Sub</th>
			      <th scope="col">Completata</th>
			      <th scope="col">Punti</th>
			      <th scope="col">Genere</th>
			      <th scope="col">Aggiunto</th>
			      <th scope="col">Ultima modifica</th>
			    </tr>
			  </thead>
			  <tbody>
			  	@if($oavs->isEmpty())
			  	<tr><p>Non ci sono OAV in archivio</p></tr>
			  	@endif
			  	@foreach($oavs as $oav)
			  		
			    <tr>
			      <th scope="row">{{ $oav->id }}</th>
			      <td>{{ $oav->name }}</td>
			      <td>{{ $oav->country()->first()->name }}</td>
			      <td>{{ str_limit($oav->plot, 70, '...') }}</td>
			      <td>{{ $oav->audio }}</td>
			      <td>{{ $oav->sub }}</td>
			      <td>{{ ($oav->completed) ? 'Si' : 'No' }}</td>
			      <td>{{ $oav->points }}</td>
			      <td>{{ $oav->genre()->first()->name }}</td>
			      <td><abbr title="{{ $oav->created_at->toDateString() }}">{{ $oav->created_at->diffForHumans() }}</abbr></td>
			      <td><abbr title="{{ $oav->updated_at->toDateString() }}">{{ $oav->updated_at->diffForHumans() }}</abbr></td>
			      <td><a href="{{ route('oav.show', ['oav' => $oav->slug]) }}" class="btn btn-primary" type="button"><i class="fab fa-readme"></i> Visualizza</button></td>
			      <td><a href="{{ route('oav.edit', ['oav' => $oav->slug]) }}" class="btn btn-danger" type="button"><i class="fas fa-pen-square"></i> Modifica</button></td>
			      <td><a href="#" class="btn btn-danger" type="button"><i class="fas fa-minus-circle"></i> Elimina</button></td>
			    </tr>
			    @endforeach
			  </tbody>
			</table>
		</div>
		<div class="col-12">
			{{ $oavs->links() }}
		</div>

	</div>
</div>


@endsection

resources/views/admin/oav/show.blade.php
 @extends('layouts.adminLayout')
@section('content')
<div class="spacer my-4"></div>
@include('components.back')
<div class="container-fluid">
	<div class="row">
		<div class="col-3 offset-2 mb-1">
			<a type="button" class="btn btn-primary btn-sm">Modifica</a>
			<a type="button" class="btn btn-primary btn-sm">Elimina</a>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3 offset-1 ml-5"> <!-- start col-md-3 -->
			<div class="card mb-3">
			  <img class="card-img-top" src="http://via.placeholder.com/150x150" alt="Card image cap">
			  <div class="card-body">
			    <h5 class="card-title">{{ $oav->name }}</h5>
			    <p class="card-text">Trama</p>
			    <p class="card-text">{{ $oav->plot }}</p>
			  </div>
			  <ul class="list-group list-group-flush">
			    <li class="list-group-item">Titolo : <strong>{{ $oav->name }}</strong></li>
			    <li class="list-group-item">Titolo alternativo : <strong>titolo alternativo</strong></li>
			    <li class="list-group-item">Genere : <strong>{{ $oav->genre()->first()->name }}</strong></li>
			    <li class="list-group-item">Anno : <strong>anno - anno</strong></li>
			    <li class="list-group-item">Episodi : <strong>{{ count($oav->episodes()) }}</strong></li>
			    <li class="list-group-item">Durata media epidosio : <strong>{{ count($oav->episodes()) }}</strong></li>
			    <li class="list-group-item">Audio : <strong>{{ count($oav->audio) }}</strong></li>
			    <li class="list-group-item">Sub : <strong>{{ count($oav->sub) }}</strong></li>
			    <li class="list-group-item">Punti : <strong>{{ $oav->points }}</strong></li>
			    <li class="list-group-item"><strong>Il tuo voto : VOTO</strong></li>
			    <li class="list-group-item">Aggiunto il : <strong>{{ $oav->created_at->toDateString() }}</strong></li>
			  </ul>
			  <div class="card-body">
			    <a href="#" class="card-link">Card link</a>
			    <a href="#" class="card-link">Another link</a>
			  </div>
			</div>
		</div> <!-- end col-md-3 (card) -->
		<div class="col-md-7"> <!-- start col-md-9 -->
			<div class="card mb-3">
				<div class="card-header">Trama</div>
				<div class="card-body">
					<p class="card-text">{{ $oav->plot }}</p>
				</div>
				<div class="card-footer">
					<p class=""></p>
				</div>
			</div>
			<div class="card mb-3">
				<div class="card-header">Reviews</div>
				<div class="card-body">
					<p class="card-text">In arrivo</p>
				</div>
				<div class="card-footer text-muted">
					Vedi qualcosa che dovrebbe essere corretto? <a href="#">Faccelo sapere</a>!
				</div>
			</div>
			<div class="card mb-3">
				<div class="card-header">Trailer</div>
				<div class="card-body">
					<p class="card-text">In arrivo</p>
				</div>
				<div class="card-footer text-muted">
					Vedi qualcosa che dovrebbe essere corretto? <a href="#">Faccelo sapere</a>!
				</div>
			</div>
			
		</div> <!-- end col -md-9 -->
	</div>
</div>
@endsection