routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//=============== MAIN\PUBLIC ROUTES ===================

 // ===== GET ROUTES ========

Route::get('/', 'HomeController@homepage')->name('home');
 
Auth::routes();

Route::get('/profile', 'HomeController@profile')->name('profile');
Route::patch('/profile', 'HomeController@profileUpdateSettings')->name('profile.update');

//Route::get('/home', 'HomeController@cp')->name('CP');

// Public animes page
Route::get('/anime', 'HomeController@animeMain')->name('anime');
Route::get('/anime/{show}', 'HomeController@showAnime')->name('anime.show');

// Public TV Shows page

Route::get('/tvshows', 'HomeController@tvShowsMain')->name('tvshows');
Route::get('/tvshows/{show}', 'HomeController@showTvShows')->name('tvshows.show');

// Public films page

Route::get('/films', 'HomeController@filmsMain')->name('films');
Route::get('/films/{show}', 'HomeController@showFilms')->name('films.show');

// Public OVAs page

Route::get('/ova', 'HomeController@ovaMain')->name('ova');
Route::get('/ova/{show}', 'HomeController@showOva')->name('ova.show');

// ====== POST ROUTES =========



//======= RESOURCES ==========


  // ADMIN


//======= ADMIN AREA ======== 
Route::group(['prefix' => 'cp'], function() {

Route::get('/', 'ControlPanelController@index')->name('CP');

Route::resource('anime', 'AnimeController');
Route::resource('film', 'FilmController');
Route::resource('tv-show', 'TvShowController');
Route::resource('oav', 'OavController');

});
//Route::get('/cp/animes', 'ControlPanelController@getAnime')->name('cp.anime.show');
// Anzichè fare un controller e una risorsa per ogni categorie che abbiamo
// mi è sembrato più logico farne uno unico per tutto quanto, e lasciare
// decidere cosa fare alla logica nel controller, in base alla
// variabile utilizzata  showtype
//Route::resource('cp/{showtype}/{show}', 'ShowController');

resources/views/layouts/adminLayout.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="icon" href="../../../../favicon.ico">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
    <meta property="og:title" content="">
    <meta property="og:image" content="logo.png">

    <title>{{ config('app.name', 'DreamSub - Anime Sub ITA') }}</title>


    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  </head>

  <body id="cp">
    <div class="sidebar">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-item sidebar-brand">
          <strong>DreamSub CP</strong>
        </li>
        <li class="sidebar-nav-item">
          <a href="{{ route('anime.index') }}">Elenco Anime</a>
        </li>
        <li class="sidebar-nav-item">
          <a href="{{ route('tv-show.index') }}">Elenco Serie TV</a>
        </li>
        <li class="sidebar-nav-item">
          <a href="{{ route('film.index') }}">Elenco Film</a>
        </li>
        <li class="sidebar-nav-item sidebar-brand">
          <strong>DreamSub CP</strong>
        </li>
        <li class="sidebar-nav-item">
          <a href="{{ route('oav.index') }}">Elenco OAV</a>
        </li>
        <li class="sidebar-nav-item">
          <a href="#">Utenti</a>
        </li>
        <li class="sidebar-nav-item">
          <a href="#">Ruoli</a>
        </li>
        <li class="sidebar-nav-item sidebar-brand">
          <strong>DreamSub CP</strong>
        </li>
        <li class="sidebar-nav-item">
          <a href="#">Link SideNav</a>
        </li>
        
      </ul>
    </div>

      @include('components.mainNavBar')

      @yield('content')

      <div class="container">
      <footer class="row justify-items-center align-items-center panelFooter">
        <div class="col-12">
          <p><small>DreamSub Control Panel v0.0.1 - <a href="#">contatta un admin</a> - <a href="#">contatta un developer</a></small></p>
        </div>
      </footer>
      </div>


    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}"></script>
  </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/layout.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <link rel="icon" href="../../../../favicon.ico">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
    <meta property="og:title" content="">
    <meta property="og:image" content="logo.png">

    <title>{{ config('app.name') }}</title>


    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  </head>

  <body>

      @include('components.mainNavBar')

      @yield('content')

    <footer class="mainFoot container-fluid">
      <div class="container">
       <div class="row">
        <div class="col-12">
          <p>Dreamsub è nato con lo scopo di creare una community di appassionati di anime. Le serie che troverete sul nostro sito non sono di nostra proprietà e noi non possediamo i diritti su di esse. La traduzione degli episodi e l'aggiunta di sottotitoli alle serie è effetuata dal team di fansub. Queste vengono poi messe sul nostro sito senza scopo di lucro. Ci impegniamo comunque a rimuovere il materiale presente licenziato in Italia che può danneggiare il lavoro di terzi.</p>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          <ul class="list-inline">
            <li class="list-inline-item"><a class="mainFooterLink" href="#">Home</a></li>&raquo;
            <li class="list-inline-item"><a class="mainFooterLink" href="#">Chi siamo?</a></li>&raquo;
            <li class="list-inline-item"><a class="mainFooterLink" href="#">Contatti</a></li>&raquo;
            <li class="list-inline-item"><a class="mainFooterLink" href="#">Termini di utilizzo</a></li>&raquo;
            <li class="list-inline-item"><a class="mainFooterLink" href="#">Privacy Policy</a></li>&raquo;
            <li class="list-inline-item"><a class="mainFooterLink" href="#">DMCA</a></li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-12">
          Copyright &copy; 2016-2018 Dreamsub All rights reserved. 
        </div>
      </div>
     </div>
    </footer>
      
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    @stack('body-scripts')
  </body>
</html>